try:
	pass
except Exception as ex:
	print(ex)
	pass